### ISSUE TITLE
Introduce .editorconfig ivm tabs vs space in code formating

### ISSUE THREAD

**Issue by jmslbam** [burovoordeboeg/wordpress-base-theme#17]
Om zaken zoals tabs vs spaces af te vangen en je een eenduidige source code formating krijgt ipv vreemde indents

Sub-optimaal: https://github.com/burovoordeboeg/zeeuw-website-theme/blob/develop/functions/facetwp.php#L175-L202

**Comment by jstreuper** [comment]
@jmslbam heb je een voorbeeld van een goede .editorconfig?

**Comment by jmslbam** [comment]
Is uiteraard afhankelijk van je eigen codingconvention voor als je PHP Code Sniffer gebruiker, maar ik zou ze baseren op 1 van deze 2 en dan moet je een eind komen:

roots/sage https://github.com/roots/sage/blob/main/.editorconfig

wordpress/core https://core.trac.wordpress.org/browser/trunk/.editorconfig
