### ISSUE TITLE
fix Error while traversing the CSS: Error:

### ISSUE THREAD

**Issue by bdfpplinsinga** [burovoordeboeg/wordpress-base-theme#33]
change add_editor_style link

**Comment by jstreuper** [comment]
@bdfpplinsinga wat bedoel je precies?

**Comment by bdfpplinsinga** [comment]
@jstreuper Dit ging om een vreemde error op live sites. Lokaal ging alles goed in de backend maar vervolgens in de frontend niet meer. Dit bleek te komen door de wijze waarop we de backend styles inladen. Dit is reeds gefixed in deze commit (https://github.com/burovoordeboeg/wordpress-base-theme/commit/cfb33f47c0cbe5ff265bb72874c3c626494af280).
